version: "3.9"

services:
  spark:
    container_name: spark-container
    build: .
    image: bees-breweries-case-spark:latest
    ports:
      - "4040:4040"  # Spark UI
    volumes:
      - .:/home/project           # monta o projeto inteiro
      - ./data/bronze:/opt/landing
      - ./data/silver:/opt/delta/silver
    environment:
      - SPARK_MODE=master
    working_dir: /home/project/scripts
    command: tail -f /dev/null  # Container fica ativo para execuções manuais
